export const USERMESSAGES = {
  VALIDATION_ERROR: 'Validation error',
  NAME_IS_REQUIRED: 'Name is required',
  NAME_MUST_BE_A_STRING: 'Name must be a string',
  NAME_LENGTH_MUST_BE_FROM_1_TO_20: 'Name must be between 1 and 20 characters',
  EMAIL_IS_REQUIRED: 'Email is required',
  INVALID_EMAIL_FORMAT: 'Invalid email format',
  EMAIL_ALREADY_EXISTS: 'Email already exists',
  PASSWORD_IS_REQUIRED: 'Password is required',
  PASSWORD_MUST_BE_A_STRING: 'Password must be a string',
  PASSWORD_LENGTH_MUST_BE_BETWEEN_6_AND_20: 'Password length must be between 6 and 20 characters',
  PASSWORD_STRONG_REQUIREMENTS:
    'Password must have a minimum length of 6 characters, at least 1 lowercase letter, 1 uppercase letter, 1 number, and 1 symbol',
  CONFIRM_PASSWORD_IS_REQUIRED: 'Confirmation password is required',
  CONFIRM_PASSWORD_MUST_BE_A_STRING: 'Confirmation password must be a string',
  CONFIRM_PASSWORD_LENGTH_MUST_BE_BETWEEN_6_AND_20: 'Confirmation password length must be between 6 and 20 characters',
  PASSWORD_CONFIRMATION_MISMATCH: 'Password confirmation does not match password',
  DATE_OF_BIRTH_IS_REQUIRED: 'Date of birth is required',
  INVALID_DATE_FORMAT: 'Invalid date format',
  USER_NOT_FOUND: 'User not found',
  ACCESS_TOKEN_IS_REQUIRED: 'Access token is required',
  REFRESH_TOKEN_IS_REQUIRED: 'Refresh token is required',
  VERIFY_EMAIL_TOKEN_IS_REQUIRED: 'Verify email token is required',
  ACCOUNT_ALREADY_VERIFIED: 'Account already verified',
  LOGOUT_SUCCESS: 'Logout successful'
};
